"""Add phone and is_active to users, add notes and estimated_delivery_time to orders

Revision ID: 43cda3fe5627
Revises: d1bda4b9f127
Create Date: 2026-05-15 19:40:49.938910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cda3fe5627'
down_revision: Union[str, Sequence[str], None] = 'd1bda4b9f127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone')
    op.drop_column('orders', 'estimated_delivery_time')
    op.drop_column('orders', 'notes')
    # ### end Alembic commands ###
